// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios'
import type {
  AirlineAgentChatRouteApiAirlineAgentStreamPostData,
  AirlineAgentChatRouteApiAirlineAgentStreamPostError,
  AirlineAgentChatRouteApiAirlineAgentStreamPostResponse
} from './types.gen'

export const client = createClient(createConfig())

/**
 * Agent Chat Route
 */
export const airlineAgentChatRouteApiAirlineAgentStreamPost = <
  ThrowOnError extends boolean = false
>(
  options: Options<
    AirlineAgentChatRouteApiAirlineAgentStreamPostData,
    ThrowOnError
  >
) => {
  return (options?.client ?? client).post<
    AirlineAgentChatRouteApiAirlineAgentStreamPostResponse,
    AirlineAgentChatRouteApiAirlineAgentStreamPostError,
    ThrowOnError
  >({
    ...options,
    url: '/api/agent/stream'
  })
}
