// This file is auto-generated by @hey-api/openapi-ts

export type EvalLog = {
  explanation?: string | null
}

export type EvalResult = {
  score?: number | null
  triggered?: boolean | null
  triggered_escalation?: boolean | null
  triggered_guardrail?: boolean | null
  log?: EvalLog | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type MessageMetadata = {
  original_llm_response?: string | null
  is_expert_answer?: boolean | null
  guardrailed?: boolean | null
  escalated_to_sme?: boolean | null
  scores?: {
    [key: string]: EvalResult
  } | null
}

export type UserMessage = {
  thread_id?: string | null
  metadata?: MessageMetadata
  role?: 'user'
  content: string
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type AirlineAgentChatRouteApiAirlineAgentStreamPostData = {
  body: UserMessage
}

export type AirlineAgentChatRouteApiAirlineAgentStreamPostResponse = unknown

export type AirlineAgentChatRouteApiAirlineAgentStreamPostError =
  HTTPValidationError
