// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-axios'
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query'
import type {
  AirlineAgentChatRouteApiAirlineAgentStreamPostData,
  AirlineAgentChatRouteApiAirlineAgentStreamPostError,
  AirlineAgentChatRouteApiAirlineAgentStreamPostResponse
} from '../types.gen'
import type { AxiosError } from 'axios'
import {
  client,
  airlineAgentChatRouteApiAirlineAgentStreamPost
} from '../services.gen'

type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
  }
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean
): QueryKey<TOptions>[0] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? client).getConfig().baseURL
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return params
}

export const airlineAgentChatRouteApiAirlineAgentStreamPostQueryKey = (
  options: Options<AirlineAgentChatRouteApiAirlineAgentStreamPostData>
) => [createQueryKey('airlineAgentChatRouteApiAirlineAgentStreamPost', options)]

export const airlineAgentChatRouteApiAirlineAgentStreamPostOptions = (
  options: Options<AirlineAgentChatRouteApiAirlineAgentStreamPostData>
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await airlineAgentChatRouteApiAirlineAgentStreamPost({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true
      })
      return data
    },
    queryKey: airlineAgentChatRouteApiAirlineAgentStreamPostQueryKey(options)
  })
}

export const airlineAgentChatRouteApiAirlineAgentStreamPostMutation = (
  options?: Partial<Options<AirlineAgentChatRouteApiAirlineAgentStreamPostData>>
) => {
  const mutationOptions: UseMutationOptions<
    AirlineAgentChatRouteApiAirlineAgentStreamPostResponse,
    AxiosError<AirlineAgentChatRouteApiAirlineAgentStreamPostError>,
    Options<AirlineAgentChatRouteApiAirlineAgentStreamPostData>
  > = {
    mutationFn: async localOptions => {
      const { data } = await airlineAgentChatRouteApiAirlineAgentStreamPost({
        ...options,
        ...localOptions,
        throwOnError: true
      })
      return data
    }
  }
  return mutationOptions
}
